apiVersion: v1
kind: PersistentVolume
metadata:
  name: podpv
  labels:
    type: podpv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podpvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  volumes:
    - name: pod-storage
      persistentVolumeClaim:
        claimName: podpvc
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/data"
          name: pod-storage