apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: qq2
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/data"
      name: pv
      readOnly: true
      recursiveReadOnly: Enabled
  volumes:
    - name: pv
      persistentVolumeClaim:
        claimName: podpvc