controlplane $ cat ngnix-pod.yaml 
apiVersion: v1
kind: Namespace
metadata:
  name: qq2
  labels:
    app: qq2
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: qq2
  labels:
    app: pod
spec:
  containers:
  - name: pod
    image: nginx:latest
    volumeMounts:
    - mountPath: /data
      name: data
      readOnly: true
    ports:
    - containerPort: 80
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: podpvc
controlplane $ cat podpvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podpvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
controlplane $ cat pv.yaml 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: gp2

  hostPath:
    path: /mnt/data
controlplane $ cat class-sc.yaml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowVolumeExpansion: false
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer
controlplane $ 
