apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: test-statefulset
  name: test-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-statefulset
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-statefulset
    spec:
      containers:
        - image: nginx:alpine
          name: nginx
          volumeMounts:
            - name: nginx-volume
              mountPath: /data
      volumes:
        - name: nginx-volume
          persistentVolumeClaim:
            claimName: data-pvc

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-fast
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
reclaimPolicy: Delete

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: sc-fast
  hostPath:
    path: /data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: sc-fast
