apiVersion: v1
kind: ConfigMap
metadata:
  name: q5-configmap
data:
  link: "http://example.com/"
---
apiVersion: v1
kind: Secret
metadata:
  name: q5-secret
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
  - name: apache
    image: httpd:latest
    ports:
    - containerPort: 80
    env:
      - name: API_LING
        valueFrom:
          configMapKeyRef:
            name: link
            key: link
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: username
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: password
            key: password