apiVersion: v1
kind: ConfigMap
metadata:
  name: q5
data:
  apiLink: "www.123.com/uri/get=123"

---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: kubernetes.io/basic-auth
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: t0p-Secret

---

apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
  - name: apache
    image: httpd:latest
    ports:
    - containerPort: 80
    env:
    - name: API_LING
      valueFrom: 
        configMapKeyRef:
          name: q5
          key: apiLink
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: credentials
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: credentials
          key: password