apiVersion: v1
kind: ConfigMap
metadata:
  name: q5
  namespace: default
data:
  api: "test"

---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: default
type: Opaque
data:
  username: "username"
  password: "password"

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: apache
  name: apache
spec:
  containers:
    - image: httpd
      name: apache
      env:
        - name: API_LING
          valueFrom:
            configMapKeyRef:
              name: q5
              key: api
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
