apiVersion: v1
kind: ConfigMap
metadata:
  name: q5
data:
  api_link: "https://localhost/api/json"
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  username: cGFzc3dvcmQ=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
    - name: apache
      image: httpd
      ports:
        - containerPort: 80
      env:
        - name: API_LINK
          valueFrom:
            configMapKeyRef:
              name: q5
              key: api_link
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password