apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cloud-app01
  name: cloud-app01
  namespace: ca2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-app01
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cloud-app01
    spec:
      containers:
        - image: nginx:1.23.3-alpine
          name: nginx
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cloud-app01
  name: cloud-app-svc
  namespace: ca2
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: cloud-app01
status:
  loadBalancer: {}
