apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: limit
spec:
  selector:
    matchLabels:
      app: limit
  replicas: 3
  template:
    metadata:
      labels:
        app: limit
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 80
          name: limit-port
        volumeMounts:
        - name: limit-volume-mount
          mountPath: /usr/local/etc/redis