apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
  namespace: fullstack
spec:
  containers:
  - image: nginx
    name: nginx
  - image: maven:3.9.9-eclipse-temurin-11
    name: java
    command: ["mvn"]
    args: ["clean", "install"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}