apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: fullstack
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
  - name: maven
    image: maven:3.9.9-eclipse-temurin-11
