apiVersion: v1
kind: Pod
metadata:
  name: q2-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: maven
    image: maven:3.9.9-eclipse-temurin-11
    ports:
    - containerPort: 81